import { ImageGenerationParams } from './schemas.js';

// Default parameters for image generation
export const defaultParams: ImageGenerationParams = {
  speed_up_with_guidance_embed: true,
  motion_scale: 127,
  image_guidance: 1.5,
  tiled_decoding: false,
  decoding_tile_height: 640,
  negative_prompt_for_image_prior: true,
  batch_size: 1,
  decoding_tile_overlap: 128,
  separate_open_clip_g: false,
  hires_fix_height: 960,
  decoding_tile_width: 640,
  diffusion_tile_height: 1024,
  num_frames: 14,
  stage_2_guidance: 1,
  t5_text_encoder_decoding: true,
  mask_blur_outset: 0,
  resolution_dependent_shift: true,
  model: "flux_1_schnell_q5p.ckpt",
  hires_fix: false,
  strength: 1,
  loras: [],
  diffusion_tile_width: 1024,
  diffusion_tile_overlap: 128,
  original_width: 512,
  seed: -1,
  zero_negative_prompt: false,
  upscaler_scale: 0,
  steps: 8,
  upscaler: null,
  mask_blur: 1.5,
  sampler: "DPM++ 2M AYS",
  width: 320,
  negative_original_width: 512,
  batch_count: 1,
  refiner_model: null,
  shift: 1,
  stage_2_shift: 1,
  open_clip_g_text: null,
  crop_left: 0,
  controls: [],
  start_frame_guidance: 1,
  original_height: 512,
  image_prior_steps: 5,
  guiding_frame_noise: 0.019999999552965164,
  clip_weight: 1,
  clip_skip: 1,
  crop_top: 0,
  negative_original_height: 512,
  preserve_original_after_inpaint: true,
  separate_clip_l: false,
  guidance_embed: 3.5,
  negative_aesthetic_score: 2.5,
  aesthetic_score: 6,
  clip_l_text: null,
  hires_fix_strength: 0.699999988079071,
  guidance_scale: 7.5,
  stochastic_sampling_gamma: 0.3,
  seed_mode: "Scale Alike",
  target_width: 512,
  hires_fix_width: 960,
  tiled_diffusion: false,
  fps: 5,
  refiner_start: 0.8500000238418579,
  height: 512,
  prompt: "A cute koala sitting on a eucalyptus tree, watercolor style, beautiful lighting, detailed",
  negative_prompt: "deformed, distorted, unnatural pose, extra limbs, blurry, low quality, ugly, bad anatomy, poor details, mutated, text, watermark"
}; 