import axios from 'axios';
import { defaultParams } from './defaultParams.js';

class DrawThingsService {
  constructor() {
    this.baseUrl = 'http://127.0.0.1:7888';
    this.axios = axios.create({
      baseURL: this.baseUrl,
      timeout: 300000, // 5 minutes timeout
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      validateStatus: function (status) {
        return status >= 200 && status < 500;
      }
    });

    // Request interceptor
    this.axios.interceptors.request.use(
      config => {
        console.log(`Sending request to ${config.url}:`, config.data);
        return config;
      },
      error => {
        console.error('Request error:', error);
        return Promise.reject(error);
      }
    );

    // Response interceptor
    this.axios.interceptors.response.use(
      response => {
        console.log('Received response:', response.status);
        if (response.data) {
          console.log('Response data:', response.data);
        }
        return response;
      },
      error => {
        console.error('Response error:', error.message);
        if (error.response) {
          console.error('Error response data:', error.response.data);
        }
        return Promise.reject(error);
      }
    );
  }

  getDefaultParams() {
    return defaultParams;
  }

  async checkApiConnection() {
    try {
      const response = await this.axios.get('/sdapi/v1/sd-models', { timeout: 5000 });
      return response.status >= 200 && response.status < 300;
    } catch (error) {
      console.error('API connection check failed:', error.message);
      return false;
    }
  }

  async generateImage(params = {}) {
    // Check API connection
    const isConnected = await this.checkApiConnection();
    if (!isConnected) {
      console.error('Draw Things API is not available');
      return {
        status: 503,
        error: 'Draw Things API is not running or cannot be connected. Please make sure Draw Things is running and the API is enabled.'
      };
    }

    // Ensure params is a valid object
    if (!params || typeof params !== 'object') {
      params = {};
    }

    // Ensure prompt exists
    if (!params.prompt) {
      params.prompt = defaultParams.prompt;
    }

    const mergedParams = {
      ...defaultParams,
      ...params,
      seed: params.seed || Math.floor(Math.random() * 2147483647)  // Generate random seed
    };

    try {
      console.log('Sending request to Draw Things API...');
      console.log('Request parameters:', mergedParams);
      
      const response = await this.axios.post('/sdapi/v1/txt2img', mergedParams);
      console.log('Received response from API');
      
      if (response.status >= 400) {
        console.error('API error:', response.data);
        return {
          status: response.status,
          error: response.data?.error || `API returned error status: ${response.status}`
        };
      }

      if (!response.data || !response.data.images || response.data.images.length === 0) {
        return {
          status: 404,
          error: 'No images were generated by the API'
        };
      }

      return {
        status: response.status,
        images: response.data.images,
        parameters: mergedParams
      };
    } catch (error) {
      console.error('API request failed:', error.message);
      if (error.response) {
        console.error('API error response:', error.response.data);
        return {
          status: error.response.status,
          error: error.response.data?.error || `API error: ${error.message}`
        };
      }
      
      // Network error handling
      if (error.code === 'ECONNREFUSED') {
        return {
          status: 503,
          error: 'Draw Things API service is not running or cannot be connected. Please make sure Draw Things is running and the API is enabled.'
        };
      }
      if (error.code === 'ETIMEDOUT') {
        return {
          status: 504,
          error: 'Request timed out, possibly due to long image generation time. The model might be loading or the generation is taking longer than expected.'
        };
      }
      
      return {
        status: 500,
        error: `Unknown error: ${error.message}`
      };
    }
  }
}

export { DrawThingsService }; 